image: maven:3.9.16-eclipse-temurin-25

pipelines:
  default:
    - step:
        name: Build Test and Package
        caches:
          - maven
        script:
          - mvn clean verify

    - step:
        name: Security Scan
        image: python:3.11
        script:
          - pip install semgrep
          - semgrep scan --config auto .

  branches:
    develop:
      - step:
          name: Build DEV
          deployment: Development
          caches:
            - maven
          script:
            - mvn clean verify

    uat:
      - step:
          name: Build UAT
          deployment: UAT
          caches:
            - maven
          script:
            - mvn clean verify

    main:
      - step:
          name: Build PROD
          deployment: Production
          caches:
            - maven
          script:
            - mvn clean verify

      - step:
          name: Security Scan
          image: python:3.11
          script:
            - pip install semgrep
            - semgrep scan --config auto .
